# Challenge 1 - Tic Tac Toe

In this lab you will perform deep learning analysis on a dataset of playing [Tic Tac Toe](https://en.wikipedia.org/wiki/Tic-tac-toe).

There are 9 grids in Tic Tac Toe that are coded as the following picture shows:

![Tic Tac Toe Grids](tttboard.jpg)

In the first 9 columns of the dataset you can find which marks (`x` or `o`) exist in the grids. If there is no mark in a certain grid, it is labeled as `b`. The last column is `class` which tells you whether Player X (who always moves first in Tic Tac Toe) wins in this configuration. Note that when `class` has the value `False`, it means either Player O wins the game or it ends up as a draw.

Follow the steps suggested below to conduct a neural network analysis using Tensorflow and Keras. You will build a deep learning model to predict whether Player X wins the game or not.

## Step 1: Data Engineering

This dataset is almost in the ready-to-use state so you do not need to worry about missing values and so on. Still, some simple data engineering is needed.

1. Read `tic-tac-toe.csv` into a dataframe.
1. Inspect the dataset. Determine if the dataset is reliable by eyeballing the data.
1. Convert the categorical values to numeric in all columns.
1. Separate the inputs and output.
1. Normalize the input data.

In [1]:
import tensorflow as tf

In [2]:
#Importing relevant libraries
import pandas as pd
import numpy as np

In [3]:
#Reading the data

df = pd.read_csv("tic-tac-toe.csv")
df

     TL   TM   TR   ML   MM   MR   BL   BM   BR   class
0    x    x    x    x    o    o    x    o    o     True
1    x    x    x    x    o    o    o    x    o     True
2    x    x    x    x    o    o    o    o    x     True
3    x    x    x    x    o    o    o    b    b     True
4    x    x    x    x    o    o    b    o    b     True
..   ..  ...  ...  ...  ...  ...  ...  ...  ...     ...
953  o    x    x    x    o    o    o    x    x    False
954  o    x    o    x    x    o    x    o    x    False
955  o    x    o    x    o    x    x    o    x    False
956  o    x    o    o    x    x    x    o    x    False
957  o    o    x    x    x    o    o    x    x    False

[958 rows x 10 columns]

In [4]:
#Data inspection

df.isnull().sum()# No missing data
df.shape # Data is 958 rows x 10 columns 
df.info() # all values are objects
df.columns #columns have an additional space in front.

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 958 entries, 0 to 957
Data columns (total 10 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   TL      958 non-null    object
 1    TM     958 non-null    object
 2    TR     958 non-null    object
 3    ML     958 non-null    object
 4    MM     958 non-null    object
 5    MR     958 non-null    object
 6    BL     958 non-null    object
 7    BM     958 non-null    object
 8    BR     958 non-null    object
 9    class  958 non-null    object
dtypes: object(10)
memory usage: 75.0+ KB

Index(['TL', ' TM', ' TR', ' ML', ' MM', ' MR', ' BL', ' BM', ' BR', ' class'], dtype='object')

In [5]:
#Data cleaning
df_clean= df.copy()
df_clean.columns = df_clean.columns.str.strip()
df_clean.columns

Index(['TL', 'TM', 'TR', 'ML', 'MM', 'MR', 'BL', 'BM', 'BR', 'class'], dtype='object')

In [6]:
df_clean = df_clean.apply(lambda x: x.str.strip())
df_clean["TL"].unique()

array(['x', 'o', 'b'], dtype=object)

In [15]:
#Converting values from categorical to numerical
# x will be 1 
# o will be 0
#True == 1
#False == 0

#Returning true or false as numeric values first: 
df_num = df_clean.replace({"True":1, "False":0,"x":1, "o":0, "b":2})
df_num

C:\Users\nicol\AppData\Local\Temp\ipykernel_23848\1265934038.py:8: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_num = df_clean.replace({"True":1, "False":0,"x":1, "o":0, "b":2})

     TL  TM  TR  ML  MM  MR  BL  BM  BR  class
0     1   1   1   1   0   0   1   0   0      1
1     1   1   1   1   0   0   0   1   0      1
2     1   1   1   1   0   0   0   0   1      1
3     1   1   1   1   0   0   0   2   2      1
4     1   1   1   1   0   0   2   0   2      1
..   ..  ..  ..  ..  ..  ..  ..  ..  ..    ...
953   0   1   1   1   0   0   0   1   1      0
954   0   1   0   1   1   0   1   0   1      0
955   0   1   0   1   0   1   1   0   1      0
956   0   1   0   0   1   1   1   0   1      0
957   0   0   1   1   1   0   0   1   1      0

[958 rows x 10 columns]

In [24]:
df_num.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 958 entries, 0 to 957
Data columns (total 10 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   TL      958 non-null    int64
 1   TM      958 non-null    int64
 2   TR      958 non-null    int64
 3   ML      958 non-null    int64
 4   MM      958 non-null    int64
 5   MR      958 non-null    int64
 6   BL      958 non-null    int64
 7   BM      958 non-null    int64
 8   BR      958 non-null    int64
 9   class   958 non-null    int64
dtypes: int64(10)
memory usage: 75.0 KB

## Step 2: Build Neural Network

To build the neural network, you can refer to your own codes you wrote while following the [Deep Learning with Python, TensorFlow, and Keras tutorial](https://www.youtube.com/watch?v=wQ8BIBpya2k) in the lesson. It's pretty similar to what you will be doing in this lab.

1. Split the training and test data.
1. Create a `Sequential` model.
1. Add several layers to your model. Make sure you use ReLU as the activation function for the middle layers. Use Softmax for the output layer because each output has a single lable and all the label probabilities add up to 1.
1. Compile the model using `adam` as the optimizer and `sparse_categorical_crossentropy` as the loss function. For metrics, use `accuracy` for now.
1. Fit the training data.
1. Evaluate your neural network model with the test data.
1. Save your model as `tic-tac-toe.model`.

In [ ]:
#Target is the class, rest is feature
target = df_num["class"]
features = df_num.drop("class",axis=1)

In [20]:
#Splitting the data: 
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(features, target, test_size=0.2,random_state=42)

In [22]:
#Checking the shape of my train data
X_train.shape

(766, 9)

In [44]:
y_train.shape

(766,)

*Defining the model:* 
1. Input shape: The features have 9 columns (766x9), so each combination should be equivalent to the target: 1 for win, 0 for loose or draw. 
2. Output is binary! there is no additional option if it is a draw.

In [117]:
#Model setup: 
import keras 
from keras import layers
from keras import ops

In [118]:
#Creating a sequential model: 
from tensorflow.keras.models import Sequential
model = Sequential() #Layer by layer

In [119]:
#Creating the layers for the model: 
from keras.optimizers import Adam
from tensorflow.keras.layers import Dense, Dropout, Input, Flatten
from tensorflow.keras.optimizers import RMSprop

model.add(Input(shape=(9,),dtype=int))  #  define the input shape
model.add(Flatten()) #flattens the inputs, it needs a 1D array
model.add(Dense(90, activation='relu', input_shape=(9,)))#Hidden layer
model.add(Dropout(0.2))#used to avoid overfitting, drops 20% of the neurons
model.add(Dense(30, activation='relu'))
model.add(Dropout(0.2))
model.add(Dense(2, activation='softmax'))

c:\Users\nicol\miniconda3\envs\tensorflow\lib\site-packages\keras\src\layers\core\dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [120]:
model.summary()
#Modifying the learning rate
opt= tf.keras.optimizers.Adam(
    learning_rate=0.01,
    epsilon=1e-07,
)
model.compile(optimizer=opt,
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

Model: "sequential_10"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ flatten_7 (Flatten)             │ (None, 9)              │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_27 (Dense)                │ (None, 90)             │           900 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_18 (Dropout)            │ (None, 90)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_28 (Dense)                │ (None, 30)             │         2,730 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_19 (Dropout)            │ (None, 30)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_29 (Dense)                │ (None, 2)              │            62 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 3,692 (14.42 KB)

 Trainable params: 3,692 (14.42 KB)

 Non-trainable params: 0 (0.00 B)

In [121]:
#Saving the model 
model.save('tic-tac-toe.keras')

## Step 3: Make Predictions

Now load your saved model and use it to make predictions on a few random rows in the test dataset. Check if the predictions are correct.

In [122]:
import keras
from keras import ops

tictactoe = keras.models.load_model("tic-tac-toe.keras")

c:\Users\nicol\miniconda3\envs\tensorflow\lib\site-packages\keras\src\saving\saving_lib.py:802: UserWarning: Skipping variable loading for optimizer 'adam', because it has 14 variables whereas the saved optimizer has 2 variables.
  saveable.load_own_variables(weights_store.get(inner_path))

In [123]:
batch_size = 60
epochs = 55

In [124]:
history = model.fit(X_train, y_train,
                    batch_size=batch_size,
                    epochs=epochs,
                    verbose=1,
                    validation_data=(X_test, y_test))

Epoch 1/55
13/13 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - accuracy: 0.5391 - loss: 0.7511 - val_accuracy: 0.6510 - val_loss: 0.5969
Epoch 2/55
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.6989 - loss: 0.5962 - val_accuracy: 0.6615 - val_loss: 0.6191
Epoch 3/55
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6816 - loss: 0.6185 - val_accuracy: 0.6615 - val_loss: 0.5854
Epoch 4/55
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.6904 - loss: 0.5923 - val_accuracy: 0.6875 - val_loss: 0.5365
Epoch 5/55
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7399 - loss: 0.5329 - val_accuracy: 0.7500 - val_loss: 0.4762
Epoch 6/55
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7824 - loss: 0.4624 - val_accuracy: 0.8177 - val_loss: 0.4113
Epoch 7/55
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.8198 - loss: 0.3874 - val_accuracy: 0.8750 - val_loss: 0.3370
Epoch 8/55
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.8553 - loss: 0.3454 - val_accuracy: 0.8958 - val_loss: 0.2851
Epoch 9/55
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8676 - loss: 0.3041 - val_accuracy: 0.9219 - val_loss: 0.2324
Epoch 10/55
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8845 - loss: 0.2651 - val_accuracy: 0.9583 - val_loss: 0.1908
Epoch 11/55
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9213 - loss: 0.2062 - val_accuracy: 0.9479 - val_loss: 0.1773
Epoch 12/55
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9528 - loss: 0.1683 - val_accuracy: 0.9531 - val_loss: 0.1565
Epoch 13/55
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9554 - loss: 0.1537 - val_accuracy: 0.9167 - val_loss: 0.1822
Epoch 14/55
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.9490 - loss: 0.1673 - val_accuracy: 0.9688 - val_loss: 0.1365
Epoch 15/55
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.9390 - loss: 0.1734 - val_accuracy: 0.9688 - val_loss: 0.1202
Epoch 16/55
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.9588 - loss: 0.1451 - val_accuracy: 0.9688 - val_loss: 0.1262
Epoch 17/55
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.9535 - loss: 0.1326 - val_accuracy: 0.9688 - val_loss: 0.1129
Epoch 18/55
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9725 - loss: 0.1111 - val_accuracy: 0.9688 - val_loss: 0.1193
Epoch 19/55
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9688 - loss: 0.1171 - val_accuracy: 0.9688 - val_loss: 0.1022
Epoch 20/55
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9773 - loss: 0.0684 - val_accuracy: 0.9688 - val_loss: 0.1029
Epoch 21/55
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9845 - loss: 0.0637 - val_accuracy: 0.9688 - val_loss: 0.1022
Epoch 22/55
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.9727 - loss: 0.0912 - val_accuracy: 0.9688 - val_loss: 0.1025
Epoch 23/55
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9834 - loss: 0.0723 - val_accuracy: 0.9688 - val_loss: 0.0969
Epoch 24/55
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9751 - loss: 0.0800 - val_accuracy: 0.9688 - val_loss: 0.0885
Epoch 25/55
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9774 - loss: 0.0681 - val_accuracy: 0.9688 - val_loss: 0.0937
Epoch 26/55
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.9863 - loss: 0.0582 - val_accuracy: 0.9688 - val_loss: 0.0937
Epoch 27/55
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.9838 - loss: 0.0494 - val_accuracy: 0.9688 - val_loss: 0.0954
Epoch 28/55
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9772 - loss: 0.0529 - val_accuracy: 0.9688 - val_loss: 0.0900
Epoch 29/55
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9841 - loss: 0.0515 - val_accuracy: 0.9688 - val_loss: 0.0958
Epoch 30/55
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9852 - loss: 0.0631 - val_accuracy: 0.9688 - val_loss: 0.0940
Epoch 31/55
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9841 - loss: 0.0443 - val_accuracy: 0.9688 - val_loss: 0.0905
Epoch 32/55
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9856 - loss: 0.0632 - val_accuracy: 0.9688 - val_loss: 0.0955
Epoch 33/55
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9812 - loss: 0.0450 - val_accuracy: 0.9427 - val_loss: 0.1047
Epoch 34/55
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9870 - loss: 0.0611 - val_accuracy: 0.9688 - val_loss: 0.1189
Epoch 35/55
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9761 - loss: 0.0823 - val_accuracy: 0.9688 - val_loss: 0.0937
Epoch 36/55
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9776 - loss: 0.0870 - val_accuracy: 0.9688 - val_loss: 0.0861
Epoch 37/55
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.9929 - loss: 0.0350 - val_accuracy: 0.9635 - val_loss: 0.0914
Epoch 38/55
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9885 - loss: 0.0541 - val_accuracy: 0.9688 - val_loss: 0.0960
Epoch 39/55
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9892 - loss: 0.0315 - val_accuracy: 0.9688 - val_loss: 0.1007
Epoch 40/55
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9785 - loss: 0.0511 - val_accuracy: 0.9635 - val_loss: 0.0974
Epoch 41/55
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9825 - loss: 0.0756 - val_accuracy: 0.9740 - val_loss: 0.0839
Epoch 42/55
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9794 - loss: 0.0499 - val_accuracy: 0.9688 - val_loss: 0.0904
Epoch 43/55
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9924 - loss: 0.0274 - val_accuracy: 0.9688 - val_loss: 0.0918
Epoch 44/55
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9959 - loss: 0.0318 - val_accuracy: 0.9688 - val_loss: 0.1045
Epoch 45/55
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9824 - loss: 0.0351 - val_accuracy: 0.9688 - val_loss: 0.0931
Epoch 46/55
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9852 - loss: 0.0359 - val_accuracy: 0.9688 - val_loss: 0.0939
Epoch 47/55
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9896 - loss: 0.0454 - val_accuracy: 0.9688 - val_loss: 0.1065
Epoch 48/55
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9856 - loss: 0.0394 - val_accuracy: 0.9688 - val_loss: 0.0822
Epoch 49/55
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9941 - loss: 0.0330 - val_accuracy: 0.9688 - val_loss: 0.0924
Epoch 50/55
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9890 - loss: 0.0403 - val_accuracy: 0.9688 - val_loss: 0.0922
Epoch 51/55
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9808 - loss: 0.0493 - val_accuracy: 0.9688 - val_loss: 0.1053
Epoch 52/55
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9915 - loss: 0.0240 - val_accuracy: 0.9635 - val_loss: 0.0929
Epoch 53/55
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9830 - loss: 0.0376 - val_accuracy: 0.9688 - val_loss: 0.1033
Epoch 54/55
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9777 - loss: 0.0615 - val_accuracy: 0.9583 - val_loss: 0.1012
Epoch 55/55
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.9811 - loss: 0.0504 - val_accuracy: 0.9688 - val_loss: 0.1239

## Step 4: Improve Your Model

Did your model achieve low loss (<0.1) and high accuracy (>0.95)? If not, try to improve your model.

But how? There are so many things you can play with in Tensorflow and in the next challenge you'll learn about these things. But in this challenge, let's just do a few things to see if they will help.

* Add more layers to your model. If the data are complex you need more layers. But don't use more layers than you need. If adding more layers does not improve the model performance you don't need additional layers.
* Adjust the learning rate when you compile the model. This means you will create a custom `tf.keras.optimizers.Adam` instance where you specify the learning rate you want. Then pass the instance to `model.compile` as the optimizer.
    * `tf.keras.optimizers.Adam` [reference](https://www.tensorflow.org/api_docs/python/tf/keras/optimizers/Adam).
    * Don't worry if you don't understand what the learning rate does. You'll learn about it in the next challenge.
* Adjust the number of epochs when you fit the training data to the model. Your model performance continues to improve as you train more epochs. But eventually it will reach the ceiling and the performance will stay the same.

In [125]:
# your code here

**Which approach(es) did you find helpful to improve your model performance?**

In [ ]:
# Increasing the number of epochs from 20 to 50
# Increasing the number of neurons in the first hidden layer from 60 to 90 
# Increasing the learning rate from 0.001 to 0.01